# Schema for the configuration files of the Real Time Delphi module.
real_time_delphi.settings:
  type: config_object
  label: 'Real Time Delphi settings'
  mapping:
    example:
      type: string
      label: 'Example'
